### PR TITLE
Compatibility with old browsers + code formatting + fixing sorttable bug

### LINKED ISSUE #14: Compatibility with old browsers + code formatting
There are two important housekeeping activities one should do -- the sooner the better.

The first being compatibility -- the current JavaScript source code benefits from post ES5 syntax such as arrow function expression ( `=>` ), `async`-`await`, `Promise`s, spread operator (`...`), `let`/`const` et cetera.  These won't work in the older browsers.  I strongly suggest the modern JavaScript should be transpiled to ES5 (or ES3) syntax so people using older browsers can use it too.  TypeScript compiler or babel -- either can be used to automate this.

Code formatting -- at various places semi-colon was used, at times it was not.  It would be useful to stick to a standard.  Same with double/single quotes and other such things.

What do you think, @samuelguebo?

### PR DESCRIPTION
**Pull request by acagastya**
Fixes #14
prettier for code formatting and typescript for compiling modern javascript to ES5 for older browsers has been added.  Additionally, the commits since last night have been added too.  (That is why the diff will be messy)

### CODE REVIEW

**Comment by acagastya** [comment]
(Resubmiting this after fixing the sorttable bug + resolving merge conflicts.)

**Comment by acagastya** [comment]
(Done)

**Comment by tacsipacsi** [comment]
You added `.vscode` to the gitignore file, but haven’t deleted the `.gitignore/settings.json` from the Git repo. This means that the file is still there and everyone cloning the repo will become a copy of it, but potentially becomes out-of-date compared to @samuelguebo’s personal copy. If you want to exclude a file from Git, you should also run `git rm <file>` (and commit the removal) in addition to adding the file to gitignore.

**Comment by acagastya** [comment]
Demo link: https://acagastya.github.io/consultation-stats/

**Comment by samuelguebo** [comment]
> Demo link: https://acagastya.github.io/consultation-stats/

Excellent work on this! Will review the code and merge shortly.

**Review by samuelguebo — APPROVED** [review]
LGTM!

**Pull request merged**
